apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: | 
    - userarn: arn:aws:iam::615299739574:role/deployment/GitHubActions
      username: github-actions
      groups:
        - system:masters