apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: | 
    - userarn: arn:aws:iam::615299739574:role/deployment/GitHubActions
      username: deployment:{{SessionName}}
      groups:
        - system:masters
# ConfigMap must be enabled during the initial cluster creation.
# Otherwise, you will need to create access through the AWS console and set the appropriate policies.