apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: | 
    - userarn: arn:aws:iam::615299739574:role/deployment/GitHubActions
      username: deployment:{{SessionName}}
      groups:
        - system:masters
# ConfigMap harus dinyalakan pada awal pembuatan cluster.
# jika tidak harus melalui create access pada aws console dan set policies-nya